services:
  - type: web
    name: portafolio2
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
      - key: NPM_VERSION
        value: 10.2.3
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
